### ISSUE TITLE
SCOPING: WORKING LIST OF BINDINGS FOR SWIFTUI

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/live_view_native#34]
Active list of all available bindings we can map. From:

[List of Bindings](https://github.com/liveview-native/liveview-client-swiftui/issues/159)

<h1>LIVEVIEW BINDINGS FOR SWIFTUI</h1>

<h2>Click Events</h2>

- [ ] `phx-click` liveview-native/liveview-native-swiftui-bindings#2 

<h2>Focus Events</h2>

- [ ] `phx-blur` liveview-native/liveview-native-swiftui-bindings#3 
- [ ] `phx-focus` liveview-native/liveview-native-swiftui-bindings#4 
- [ ] `phx-window-blur` liveview-native/liveview-native-swiftui-bindings#5 
- [ ] `phx-window-focus` liveview-native/liveview-native-swiftui-bindings#6 

<h2>Key Events</h2>

- [ ] `phx-keydown` liveview-native/liveview-native-swiftui-bindings#7 
- [ ] `phx-window-keydown` liveview-native/liveview-native-swiftui-bindings#8
